# CityFlo Bus Service Metro Cities
# Data Understanding and Data Cleaning

## Introduction

Real-world datasets are rarely perfect. They often contain missing values, duplicate records, inconsistent formats, incorrect data types, invalid entries, and other quality issues that can affect analysis and machine learning models.

Before performing exploratory data analysis (EDA), it is essential to thoroughly understand the dataset and improve its quality through systematic preprocessing.

The objective of this notebook is to build a robust and reusable data preprocessing pipeline capable of handling common data quality problems automatically. Rather than cleaning only the current dataset, the workflow is designed to adapt to future datasets with similar structures but different data patterns.

This notebook is divided into two major phases:

### Phase 1 — Data Understanding

The first phase focuses on understanding the dataset by examining:

- Dataset dimensions
- Feature information
- Data types
- Missing values
- Duplicate records
- Memory usage
- Statistical summaries
- Potential data quality issues

Understanding the data before modification helps identify problems and ensures informed preprocessing decisions.

### Phase 2 — Data Cleaning

The second phase performs comprehensive preprocessing to improve data quality by handling:

- Missing values
- Duplicate records
- Incorrect data types
- Invalid categorical values
- Inconsistent text formatting
- Date and time conversion
- Boolean standardization
- Numeric conversion
- Outlier detection
- Data validation
- Feature consistency checks

The resulting dataset becomes cleaner, more consistent, and better suited for exploratory data analysis, visualization, and predictive modeling.

In [10]:
# ==========================================================
# Data Manipulation
# ==========================================================
import pandas as pd
import numpy as np

# ==========================================================
# Data Visualization (used later in EDA)
# ==========================================================
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================================
# Statistical Analysis
# ==========================================================
from scipy import stats

# ==========================================================
# Date and Time Handling
# ==========================================================
from datetime import datetime
import warnings

# ==========================================================
# Display Settings
# ==========================================================
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)
pd.set_option("display.max_colwidth", None)

# ==========================================================
# Ignore Unnecessary Warnings
# ==========================================================
warnings.filterwarnings("ignore")

print("Libraries imported successfully.")

Libraries imported successfully.

## Load Dataset

The dataset is loaded into a pandas DataFrame for further inspection and preprocessing. After loading, the first few records are displayed to verify that the data has been imported correctly.

In [11]:
df = pd.read_csv("/kaggle/input/datasets/satyakidas07/cityflow-bus-service-metro-cities/cityflo_bus_service_metro_cities.csv")
df.head()

,trip_id,booking_id,customer_id,customer_name,gender,age,city,route_id,route_name,origin_stop,destination_stop,bus_number,bus_type,driver_id,driver_name,trip_date,scheduled_departure,actual_departure,scheduled_arrival,actual_arrival,distance_km,fare_inr,discount_inr,payment_mode,booking_channel,seat_number,trip_status,cancellation_reason,rating,occupancy_pct,weather,is_peak_hour,subscription_type,device_type,gps_enabled,complaint_raised
0,TRP000768,BK47984879,CUST01278,Shalini Verma,Female,21.0,Mumbai,RTMU005,Lower Parel - Mulund,Lower Parel,Mulund,MH23CF4441,AC Sleeper,DRV0080,Aarav Bhat,2024-09-21,20:25,20:25,20:58,20:58,10.9,153,0.0,UPI,Corporate Portal,D8,Completed,NaN,5.0,84.6,Haze,0,Corporate Plan,iOS,true,No
1,TRP002439,BK14257322,CUST01290,Kalpana Chopra,Male,24.0,Hyderabad,RTHY038,HITEC City - Kondapur,HITEC City,Kondapur,TS27CF8651,AC Seater,DRV0068,Sanjay Joshi,2024-08-08,14:50,15:12,15:29,15:51,14.1,127,0.0,Debit Card,Kiosk,D7,Delayed-Completed,NaN,NaN,28.3,Heavy Rain,False,Weekly Pass,Android,True,0
2,TRP000793,BK67236768,CUST01285,Sai Naidu,Female,18.0,Pune,RTPU012,Aundh - Magarpatta,Aundh,Magarpatta,MH24CF3646,AC Seater,DRV0001,Lakshmi Patel,2024-03-19,08:15,08:15,09:42,09:42,27.6,234,19.0,Cash,Corporate Portal,D11,Completed,NaN,3.0,15.4,Cloudy,1,Single Ride,Android,Yes,No
3,TRP002802,BK59659578,CUST00625,Priya Patel,Female,23.0,Mumbai,RTMU010,Ghatkopar - Lower Parel,Ghatkopar,Lower Parel,MH13CF5853,AC Sleeper,DRV0036,Siddharth Kumar,2024-12-29,17:45,17:45,18:57,NaN,28.6,310,0.0,Debit Card,Corporate Portal,D11,No-show,Customer Request,NaN,68.1,Clear,No,Corporate Plan,Web,1,Yes
4,TRP001653,BK19231279,CUST00276,Shalini Kulkarni,F,20.0,Bangalore,RTBA024,Hebbal - Electronic City,Hebbal,Electronic City,KA22CF6238,AC Seater,DRV0045,Sunita Gupta,2024-05-15,13:00,13:40,13:35,14:15,17.8,202,0.0,UPI,Corporate Portal,A1,Delayed-Completed,NaN,NaN,23.7,Haze,No,Corporate Plan,iOS,True,0

## Basic Dataset Information

Before cleaning the data, it is important to understand its overall structure. This includes the number of observations, number of features, memory usage, and data types stored within the dataset.

These details help identify potential preprocessing requirements such as datatype conversion, missing values, or memory optimization.

In [12]:
print(f"Number of Rows    : {df.shape[0]}")
print(f"Number of Columns : {df.shape[1]}")

print("\nDataset Shape:")
print(df.shape)

print("\nMemory Usage (MB):")
print(round(df.memory_usage(deep=True).sum() / (1024 ** 2), 2), "MB")

Number of Rows    : 3258
Number of Columns : 36

Dataset Shape:
(3258, 36)

Memory Usage (MB):
5.5 MB

## Dataset Overview

A detailed understanding of each feature is essential before applying any preprocessing techniques. This section provides comprehensive information about every column, including its data type, missing values, number of unique values, memory consumption, and sample values.

The overview helps identify potential issues such as:

- Incorrect data types
- Missing values
- High-cardinality features
- Constant columns
- Identifier columns
- Features requiring encoding
- Features requiring standardization

In [13]:
print("DATASET INFORMATION")
df.info()

DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3258 entries, 0 to 3257
Data columns (total 36 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   trip_id              3258 non-null   object
 1   booking_id           3258 non-null   object
 2   customer_id          3258 non-null   object
 3   customer_name        3258 non-null   object
 4   gender               3258 non-null   object
 5   age                  3194 non-null   float64
 6   city                 3258 non-null   object
 7   route_id             3258 non-null   object
 8   route_name           3258 non-null   object
 9   origin_stop          3258 non-null   object
 10  destination_stop     3258 non-null   object
 11  bus_number           3258 non-null   object
 12  bus_type             3258 non-null   object
 13  driver_id            3258 non-null   object
 14  driver_name          3226 non-null   object
 15  trip_date            3258 non-null   object
 16  scheduled_departure  3258 non-null   object
 17  actual_departure     2878 non-null   object
 18  scheduled_arrival    3258 non-null   object
 19  actual_arrival       2538 non-null   object
 20  distance_km          3258 non-null   float64
 21  fare_inr             3258 non-null   object
 22  discount_inr         3074 non-null   float64
 23  payment_mode         2878 non-null   object
 24  booking_channel      3258 non-null   object
 25  seat_number          3258 non-null   object
 26  trip_status          3258 non-null   object
 27  cancellation_reason  720 non-null    object
 28  rating               2183 non-null   float64
 29  occupancy_pct        2878 non-null   float64
 30  weather              3258 non-null   object
 31  is_peak_hour         3258 non-null   object
 32  subscription_type    3258 non-null   object
 33  device_type          3258 non-null   object
 34  gps_enabled          3258 non-null   object
 35  complaint_raised     3258 non-null   object
dtypes: float64(5), object(31)
memory usage: 916.4+ KB

## Column-wise Metadata

To better understand the characteristics of each feature, a metadata summary is generated. This table provides important information about every column, including:

- Data type
- Missing values
- Missing percentage
- Number of unique values
- Memory usage
- Sample values

This detailed overview assists in planning appropriate preprocessing steps for each feature.

In [14]:
column_summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Non-Null Count": df.count().values,
    "Missing Values": df.isnull().sum().values,
    "Missing (%)": (
        (df.isnull().sum() / len(df)) * 100
    ).round(2).values,
    "Unique Values": df.nunique().values,
    "Memory (KB)": (
        df.memory_usage(deep=True)[1:] / 1024
    ).round(2).values
})

column_summary

                 Column Data Type  Non-Null Count  Missing Values  Missing (%)  Unique Values  Memory (KB)
0               trip_id    object            3258               0         0.00           3200       184.54
1            booking_id    object            3258               0         0.00           3200       187.72
2           customer_id    object            3258               0         0.00           1251       184.54
3         customer_name    object            3258               0         0.00            866       193.61
4                gender    object            3258               0         0.00             11       169.42
5                   age   float64            3194              64         1.96             40        25.45
6                  city    object            3258               0         0.00             12       179.50
7              route_id    object            3258               0         0.00             60       178.17
8            route_name    object            3258               0         0.00             60       222.41
9           origin_stop    object            3258               0         0.00             40       184.48
10     destination_stop    object            3258               0         0.00             38       184.29
11           bus_number    object            3258               0         0.00            160       187.72
12             bus_type    object            3258               0         0.00              4       189.39
13            driver_id    object            3258               0         0.00             90       178.17
14          driver_name    object            3226              32         0.98             88       192.14
15            trip_date    object            3258               0         0.00           1113       189.31
16  scheduled_departure    object            3258               0         0.00            204       171.81
17     actual_departure    object            2878             380        11.66            768       163.64
18    scheduled_arrival    object            3258               0         0.00            956       171.81
19       actual_arrival    object            2538             720        22.10            915       156.34
20          distance_km   float64            3258               0         0.00             56        25.45
21             fare_inr    object            3258               0         0.00            953       175.89
22         discount_inr   float64            3074             184         5.65            148        25.45
23         payment_mode    object            2878             380        11.66              6       170.51
24      booking_channel    object            3258               0         0.00              4       186.15
25          seat_number    object            3258               0         0.00             60       163.48
26          trip_status    object            3258               0         0.00              4       186.92
27  cancellation_reason    object             720            2538        77.90              6       124.45
28               rating   float64            2183            1075        33.00              5        25.45
29        occupancy_pct   float64            2878             380        11.66            838        25.45
30              weather    object            3258               0         0.00              6       172.79
31         is_peak_hour    object            3258               0         0.00              6       164.41
32    subscription_type    object            3258               0         0.00              4       194.15
33          device_type    object            3258               0         0.00              3       169.77
34          gps_enabled    object            3258               0         0.00             10       164.24
35     complaint_raised    object            3258               0         0.00              4       160.76

## Sample Values

Inspecting representative values from each feature provides an initial understanding of the data stored within the column. It also helps identify formatting inconsistencies, unexpected symbols, abbreviations, and possible data entry errors.

In [15]:
sample_values = pd.DataFrame({
    "Column": df.columns,
    "Sample Values": [
        ", ".join(map(str, df[col].dropna().unique()[:5]))
        for col in df.columns
    ]
})

sample_values

,Column,Sample Values
0,trip_id,"TRP000768, TRP002439, TRP000793, TRP002802, TRP001653"
1,booking_id,"BK47984879, BK14257322, BK67236768, BK59659578, BK19231279"
2,customer_id,"CUST01278, CUST01290, CUST01285, CUST00625, CUST00276"
3,customer_name,"Shalini Verma, Kalpana Chopra, Sai Naidu, Priya Patel, Shalini Kulkarni"
4,gender,"Female , Male, Female, F, Male"
5,age,"21.0, 24.0, 18.0, 23.0, 20.0"
6,city,"Mumbai, Hyderabad, Pune, Bangalore, Delhi NCR"
7,route_id,"RTMU005, RTHY038, RTPU012, RTMU010, RTBA024"
8,route_name,"Lower Parel - Mulund, HITEC City - Kondapur, Aundh - Magarpatta, Ghatkopar - Lower Parel, Hebbal - Electronic City"
9,origin_stop,"Lower Parel, HITEC City, Aundh, Ghatkopar, Hebbal"
10,destination_stop,"Mulund, Kondapur, Magarpatta, Lower Parel, Electronic City"
11,bus_number,"MH23CF4441, TS27CF8651, MH24CF3646, MH13CF5853, KA22CF6238"
12,bus_type,"AC Sleeper, AC Seater, Premium AC, Non-AC Seater"
13,driver_id,"DRV0080, DRV0068, DRV0001, DRV0036, DRV0045"
14,driver_name,"Aarav Bhat, Sanjay Joshi, Lakshmi Patel, Siddharth Kumar, Sunita Gupta"
15,trip_date,"2024-09-21, 2024-08-08, 2024-03-19, 2024-12-29, 2024-05-15"
16,scheduled_departure,"20:25, 14:50, 08:15, 17:45, 13:00"
17,actual_departure,"20:25, 15:12, 08:15, 17:45, 13:40"
18,scheduled_arrival,"20:58, 15:29, 09:42, 18:57, 13:35"
19,actual_arrival,"20:58, 15:51, 09:42, 14:15, 09:37"
20,distance_km,"10.9, 14.1, 27.6, 28.6, 17.8"
21,fare_inr,"153, 127, 234, 310, 202"
22,discount_inr,"0.0, 19.0, 56.0, 47.0, 54.0"
23,payment_mode,"UPI, Debit Card, Cash, Wallet, Credit Card"
24,booking_channel,"Corporate Portal, Kiosk, Website, Mobile App"
25,seat_number,"D8, D7, D11, A1, A2"
26,trip_status,"Completed, Delayed-Completed, No-show, Cancelled"
27,cancellation_reason,"Customer Request, Driver Unavailable, Payment Failed, Traffic/Weather, Bus Breakdown"
28,rating,"5.0, 3.0, 2.0, 4.0, 1.0"
29,occupancy_pct,"84.6, 28.3, 15.4, 68.1, 23.7"
30,weather,"Haze, Heavy Rain, Cloudy, Clear, Rain"
31,is_peak_hour,"0, False, 1, No, True"
32,subscription_type,"Corporate Plan, Weekly Pass, Single Ride, Monthly Pass"
33,device_type,"iOS, Android, Web"
34,gps_enabled,"true, True, Yes, 1, Y"
35,complaint_raised,"No, 0, Yes, 1"

## Statistical Summary of Numerical Features

Numerical variables are summarized using descriptive statistics such as:

- Count
- Mean
- Standard deviation
- Minimum
- Quartiles
- Maximum

These statistics help identify unusual distributions, potential outliers, and impossible values that may require preprocessing.

In [16]:
df.describe().T

                count       mean        std   min   25%   50%   75%    max
age            3194.0  29.477145   8.251467  -5.0  23.0  29.0  35.0  130.0
distance_km    3258.0  24.696071  10.311346   8.3  16.0  25.7  33.1   41.8
discount_inr   3074.0  14.365973  31.070065   0.0   0.0   0.0   8.0  203.0
rating         2183.0   3.798443   1.163396   1.0   3.0   4.0   5.0    5.0
occupancy_pct  2878.0  58.313343  25.073318  15.1  36.7  58.5  79.5  138.8

## Statistical Summary of Categorical Features

Categorical variables are summarized to identify:

- Total observations
- Number of unique categories
- Most frequent category
- Frequency of the most common category

Understanding categorical features helps identify inconsistent spellings, rare categories, and potential standardization requirements.

In [17]:
categorical_summary = (
    df.select_dtypes(include="object")
      .describe()
      .T
)

categorical_summary

                    count unique               top  freq
trip_id              3258   3200         TRP002507     2
booking_id           3258   3200        BK70609800     2
customer_id          3258   1251         CUST00449     9
customer_name        3258    866         Isha Shah    22
gender               3258     11            Female   451
city                 3258     12              Pune   546
route_id             3258     60           RTCH050    69
route_name           3258     60  Tambaram - Adyar    69
origin_stop          3258     40        Thane West   225
destination_stop     3258     38        Magarpatta   168
bus_number           3258    160        KA03CF1058    39
bus_type             3258      4     Non-AC Seater   839
driver_id            3258     90           DRV0082    49
driver_name          3226     88      Sanjay Desai    69
trip_date            3258   1113        2024-07-22    12
scheduled_departure  3258    204             18:15    41
actual_departure     2878    768             18:15    26
scheduled_arrival    3258    956             09:42    12
actual_arrival       2538    915             20:55    11
fare_inr             3258    953                 0   317
payment_mode         2878      6               UPI   498
booking_channel      3258      4           Website   861
seat_number          3258     60                D7    76
trip_status          3258      4         Completed  2148
cancellation_reason   720      6  Customer Request   315
weather              3258      6               Fog   579
is_peak_hour         3258      6             False   671
subscription_type    3258      4    Corporate Plan   839
device_type          3258      3           Android  1107
gps_enabled          3258     10              true   614
complaint_raised     3258      4                 0  1544

## Automatic Feature Categorization

To make the preprocessing pipeline adaptable to future datasets, features are automatically categorized based on their data types.

This dynamic approach ensures that preprocessing steps remain applicable even if additional columns are introduced or existing columns are modified.

In [18]:
numerical_cols = df.select_dtypes(include=np.number).columns.tolist()

categorical_cols = df.select_dtypes(include="object").columns.tolist()

datetime_cols = df.select_dtypes(include=["datetime64[ns]"]).columns.tolist()

print(f"Numerical Features   : {len(numerical_cols)}")
print(numerical_cols)

print("\nCategorical Features :", len(categorical_cols))
print(categorical_cols)

print("\nDatetime Features    :", len(datetime_cols))
print(datetime_cols)

Numerical Features   : 5
['age', 'distance_km', 'discount_inr', 'rating', 'occupancy_pct']

Categorical Features : 31
['trip_id', 'booking_id', 'customer_id', 'customer_name', 'gender', 'city', 'route_id', 'route_name', 'origin_stop', 'destination_stop', 'bus_number', 'bus_type', 'driver_id', 'driver_name', 'trip_date', 'scheduled_departure', 'actual_departure', 'scheduled_arrival', 'actual_arrival', 'fare_inr', 'payment_mode', 'booking_channel', 'seat_number', 'trip_status', 'cancellation_reason', 'weather', 'is_peak_hour', 'subscription_type', 'device_type', 'gps_enabled', 'complaint_raised']

Datetime Features    : 0
[]