# CityFlo Bus Service Metro Cities
# Data Understanding and Data Cleaning

## Introduction

Real-world datasets are rarely perfect. They often contain missing values, duplicate records, inconsistent formats, incorrect data types, invalid entries, and other quality issues that can affect analysis and machine learning models.

Before performing exploratory data analysis (EDA), it is essential to thoroughly understand the dataset and improve its quality through systematic preprocessing.

The objective of this notebook is to build a robust and reusable data preprocessing pipeline capable of handling common data quality problems automatically. Rather than cleaning only the current dataset, the workflow is designed to adapt to future datasets with similar structures but different data patterns.

This notebook is divided into two major phases:

### Phase 1 — Data Understanding

The first phase focuses on understanding the dataset by examining:

- Dataset dimensions
- Feature information
- Data types
- Missing values
- Duplicate records
- Memory usage
- Statistical summaries
- Potential data quality issues

Understanding the data before modification helps identify problems and ensures informed preprocessing decisions.

### Phase 2 — Data Cleaning

The second phase performs comprehensive preprocessing to improve data quality by handling:

- Missing values
- Duplicate records
- Incorrect data types
- Invalid categorical values
- Inconsistent text formatting
- Date and time conversion
- Boolean standardization
- Numeric conversion
- Outlier detection
- Data validation
- Feature consistency checks

The resulting dataset becomes cleaner, more consistent, and better suited for exploratory data analysis, visualization, and predictive modeling.

In [52]:
# ==========================================================
# Data Manipulation
# ==========================================================
import pandas as pd
import numpy as np

# ==========================================================
# Data Visualization (used later in EDA)
# ==========================================================
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================================
# Statistical Analysis
# ==========================================================
from scipy import stats

# ==========================================================
# Date and Time Handling
# ==========================================================
from datetime import datetime
import warnings

# ==========================================================
# Display Settings
# ==========================================================
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)
pd.set_option("display.max_colwidth", None)

# ==========================================================
# Ignore Unnecessary Warnings
# ==========================================================
warnings.filterwarnings("ignore")

print("Libraries imported successfully.")

Libraries imported successfully.

## Load Dataset

The dataset is loaded into a pandas DataFrame for further inspection and preprocessing. After loading, the first few records are displayed to verify that the data has been imported correctly.

In [53]:
df = pd.read_csv("/kaggle/input/datasets/satyakidas07/cityflow-bus-service-metro-cities/cityflo_bus_service_metro_cities.csv")
df.head()

,trip_id,booking_id,customer_id,customer_name,gender,age,city,route_id,route_name,origin_stop,destination_stop,bus_number,bus_type,driver_id,driver_name,trip_date,scheduled_departure,actual_departure,scheduled_arrival,actual_arrival,distance_km,fare_inr,discount_inr,payment_mode,booking_channel,seat_number,trip_status,cancellation_reason,rating,occupancy_pct,weather,is_peak_hour,subscription_type,device_type,gps_enabled,complaint_raised
0,TRP000768,BK47984879,CUST01278,Shalini Verma,Female,21.0,Mumbai,RTMU005,Lower Parel - Mulund,Lower Parel,Mulund,MH23CF4441,AC Sleeper,DRV0080,Aarav Bhat,2024-09-21,20:25,20:25,20:58,20:58,10.9,153,0.0,UPI,Corporate Portal,D8,Completed,NaN,5.0,84.6,Haze,0,Corporate Plan,iOS,true,No
1,TRP002439,BK14257322,CUST01290,Kalpana Chopra,Male,24.0,Hyderabad,RTHY038,HITEC City - Kondapur,HITEC City,Kondapur,TS27CF8651,AC Seater,DRV0068,Sanjay Joshi,2024-08-08,14:50,15:12,15:29,15:51,14.1,127,0.0,Debit Card,Kiosk,D7,Delayed-Completed,NaN,NaN,28.3,Heavy Rain,False,Weekly Pass,Android,True,0
2,TRP000793,BK67236768,CUST01285,Sai Naidu,Female,18.0,Pune,RTPU012,Aundh - Magarpatta,Aundh,Magarpatta,MH24CF3646,AC Seater,DRV0001,Lakshmi Patel,2024-03-19,08:15,08:15,09:42,09:42,27.6,234,19.0,Cash,Corporate Portal,D11,Completed,NaN,3.0,15.4,Cloudy,1,Single Ride,Android,Yes,No
3,TRP002802,BK59659578,CUST00625,Priya Patel,Female,23.0,Mumbai,RTMU010,Ghatkopar - Lower Parel,Ghatkopar,Lower Parel,MH13CF5853,AC Sleeper,DRV0036,Siddharth Kumar,2024-12-29,17:45,17:45,18:57,NaN,28.6,310,0.0,Debit Card,Corporate Portal,D11,No-show,Customer Request,NaN,68.1,Clear,No,Corporate Plan,Web,1,Yes
4,TRP001653,BK19231279,CUST00276,Shalini Kulkarni,F,20.0,Bangalore,RTBA024,Hebbal - Electronic City,Hebbal,Electronic City,KA22CF6238,AC Seater,DRV0045,Sunita Gupta,2024-05-15,13:00,13:40,13:35,14:15,17.8,202,0.0,UPI,Corporate Portal,A1,Delayed-Completed,NaN,NaN,23.7,Haze,No,Corporate Plan,iOS,True,0

## Basic Dataset Information

Before cleaning the data, it is important to understand its overall structure. This includes the number of observations, number of features, memory usage, and data types stored within the dataset.

These details help identify potential preprocessing requirements such as datatype conversion, missing values, or memory optimization.

In [54]:
print(f"Number of Rows    : {df.shape[0]}")
print(f"Number of Columns : {df.shape[1]}")

print("\nDataset Shape:")
print(df.shape)

print("\nMemory Usage (MB):")
print(round(df.memory_usage(deep=True).sum() / (1024 ** 2), 2), "MB")

Number of Rows    : 3258
Number of Columns : 36

Dataset Shape:
(3258, 36)

Memory Usage (MB):
5.5 MB

## Dataset Overview

A detailed understanding of each feature is essential before applying any preprocessing techniques. This section provides comprehensive information about every column, including its data type, missing values, number of unique values, memory consumption, and sample values.

The overview helps identify potential issues such as:

- Incorrect data types
- Missing values
- High-cardinality features
- Constant columns
- Identifier columns
- Features requiring encoding
- Features requiring standardization

In [55]:
print("DATASET INFORMATION")
df.info()

DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3258 entries, 0 to 3257
Data columns (total 36 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   trip_id              3258 non-null   object
 1   booking_id           3258 non-null   object
 2   customer_id          3258 non-null   object
 3   customer_name        3258 non-null   object
 4   gender               3258 non-null   object
 5   age                  3194 non-null   float64
 6   city                 3258 non-null   object
 7   route_id             3258 non-null   object
 8   route_name           3258 non-null   object
 9   origin_stop          3258 non-null   object
 10  destination_stop     3258 non-null   object
 11  bus_number           3258 non-null   object
 12  bus_type             3258 non-null   object
 13  driver_id            3258 non-null   object
 14  driver_name          3226 non-null   object
 15  trip_date            3258 non-null   object
 16  scheduled_departure  3258 non-null   object
 17  actual_departure     2878 non-null   object
 18  scheduled_arrival    3258 non-null   object
 19  actual_arrival       2538 non-null   object
 20  distance_km          3258 non-null   float64
 21  fare_inr             3258 non-null   object
 22  discount_inr         3074 non-null   float64
 23  payment_mode         2878 non-null   object
 24  booking_channel      3258 non-null   object
 25  seat_number          3258 non-null   object
 26  trip_status          3258 non-null   object
 27  cancellation_reason  720 non-null    object
 28  rating               2183 non-null   float64
 29  occupancy_pct        2878 non-null   float64
 30  weather              3258 non-null   object
 31  is_peak_hour         3258 non-null   object
 32  subscription_type    3258 non-null   object
 33  device_type          3258 non-null   object
 34  gps_enabled          3258 non-null   object
 35  complaint_raised     3258 non-null   object
dtypes: float64(5), object(31)
memory usage: 916.4+ KB

## Column-wise Metadata

To better understand the characteristics of each feature, a metadata summary is generated. This table provides important information about every column, including:

- Data type
- Missing values
- Missing percentage
- Number of unique values
- Memory usage
- Sample values

This detailed overview assists in planning appropriate preprocessing steps for each feature.

In [56]:
column_summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Non-Null Count": df.count().values,
    "Missing Values": df.isnull().sum().values,
    "Missing (%)": (
        (df.isnull().sum() / len(df)) * 100
    ).round(2).values,
    "Unique Values": df.nunique().values,
    "Memory (KB)": (
        df.memory_usage(deep=True)[1:] / 1024
    ).round(2).values
})

column_summary

                 Column Data Type  Non-Null Count  Missing Values  Missing (%)  Unique Values  Memory (KB)
0               trip_id    object            3258               0         0.00           3200       184.54
1            booking_id    object            3258               0         0.00           3200       187.72
2           customer_id    object            3258               0         0.00           1251       184.54
3         customer_name    object            3258               0         0.00            866       193.61
4                gender    object            3258               0         0.00             11       169.42
5                   age   float64            3194              64         1.96             40        25.45
6                  city    object            3258               0         0.00             12       179.50
7              route_id    object            3258               0         0.00             60       178.17
8            route_name    object            3258               0         0.00             60       222.41
9           origin_stop    object            3258               0         0.00             40       184.48
10     destination_stop    object            3258               0         0.00             38       184.29
11           bus_number    object            3258               0         0.00            160       187.72
12             bus_type    object            3258               0         0.00              4       189.39
13            driver_id    object            3258               0         0.00             90       178.17
14          driver_name    object            3226              32         0.98             88       192.14
15            trip_date    object            3258               0         0.00           1113       189.31
16  scheduled_departure    object            3258               0         0.00            204       171.81
17     actual_departure    object            2878             380        11.66            768       163.64
18    scheduled_arrival    object            3258               0         0.00            956       171.81
19       actual_arrival    object            2538             720        22.10            915       156.34
20          distance_km   float64            3258               0         0.00             56        25.45
21             fare_inr    object            3258               0         0.00            953       175.89
22         discount_inr   float64            3074             184         5.65            148        25.45
23         payment_mode    object            2878             380        11.66              6       170.51
24      booking_channel    object            3258               0         0.00              4       186.15
25          seat_number    object            3258               0         0.00             60       163.48
26          trip_status    object            3258               0         0.00              4       186.92
27  cancellation_reason    object             720            2538        77.90              6       124.45
28               rating   float64            2183            1075        33.00              5        25.45
29        occupancy_pct   float64            2878             380        11.66            838        25.45
30              weather    object            3258               0         0.00              6       172.79
31         is_peak_hour    object            3258               0         0.00              6       164.41
32    subscription_type    object            3258               0         0.00              4       194.15
33          device_type    object            3258               0         0.00              3       169.77
34          gps_enabled    object            3258               0         0.00             10       164.24
35     complaint_raised    object            3258               0         0.00              4       160.76

## Sample Values

Inspecting representative values from each feature provides an initial understanding of the data stored within the column. It also helps identify formatting inconsistencies, unexpected symbols, abbreviations, and possible data entry errors.

In [57]:
sample_values = pd.DataFrame({
    "Column": df.columns,
    "Sample Values": [
        ", ".join(map(str, df[col].dropna().unique()[:5]))
        for col in df.columns
    ]
})

sample_values

,Column,Sample Values
0,trip_id,"TRP000768, TRP002439, TRP000793, TRP002802, TRP001653"
1,booking_id,"BK47984879, BK14257322, BK67236768, BK59659578, BK19231279"
2,customer_id,"CUST01278, CUST01290, CUST01285, CUST00625, CUST00276"
3,customer_name,"Shalini Verma, Kalpana Chopra, Sai Naidu, Priya Patel, Shalini Kulkarni"
4,gender,"Female , Male, Female, F, Male"
5,age,"21.0, 24.0, 18.0, 23.0, 20.0"
6,city,"Mumbai, Hyderabad, Pune, Bangalore, Delhi NCR"
7,route_id,"RTMU005, RTHY038, RTPU012, RTMU010, RTBA024"
8,route_name,"Lower Parel - Mulund, HITEC City - Kondapur, Aundh - Magarpatta, Ghatkopar - Lower Parel, Hebbal - Electronic City"
9,origin_stop,"Lower Parel, HITEC City, Aundh, Ghatkopar, Hebbal"
10,destination_stop,"Mulund, Kondapur, Magarpatta, Lower Parel, Electronic City"
11,bus_number,"MH23CF4441, TS27CF8651, MH24CF3646, MH13CF5853, KA22CF6238"
12,bus_type,"AC Sleeper, AC Seater, Premium AC, Non-AC Seater"
13,driver_id,"DRV0080, DRV0068, DRV0001, DRV0036, DRV0045"
14,driver_name,"Aarav Bhat, Sanjay Joshi, Lakshmi Patel, Siddharth Kumar, Sunita Gupta"
15,trip_date,"2024-09-21, 2024-08-08, 2024-03-19, 2024-12-29, 2024-05-15"
16,scheduled_departure,"20:25, 14:50, 08:15, 17:45, 13:00"
17,actual_departure,"20:25, 15:12, 08:15, 17:45, 13:40"
18,scheduled_arrival,"20:58, 15:29, 09:42, 18:57, 13:35"
19,actual_arrival,"20:58, 15:51, 09:42, 14:15, 09:37"
20,distance_km,"10.9, 14.1, 27.6, 28.6, 17.8"
21,fare_inr,"153, 127, 234, 310, 202"
22,discount_inr,"0.0, 19.0, 56.0, 47.0, 54.0"
23,payment_mode,"UPI, Debit Card, Cash, Wallet, Credit Card"
24,booking_channel,"Corporate Portal, Kiosk, Website, Mobile App"
25,seat_number,"D8, D7, D11, A1, A2"
26,trip_status,"Completed, Delayed-Completed, No-show, Cancelled"
27,cancellation_reason,"Customer Request, Driver Unavailable, Payment Failed, Traffic/Weather, Bus Breakdown"
28,rating,"5.0, 3.0, 2.0, 4.0, 1.0"
29,occupancy_pct,"84.6, 28.3, 15.4, 68.1, 23.7"
30,weather,"Haze, Heavy Rain, Cloudy, Clear, Rain"
31,is_peak_hour,"0, False, 1, No, True"
32,subscription_type,"Corporate Plan, Weekly Pass, Single Ride, Monthly Pass"
33,device_type,"iOS, Android, Web"
34,gps_enabled,"true, True, Yes, 1, Y"
35,complaint_raised,"No, 0, Yes, 1"

## Statistical Summary of Numerical Features

Numerical variables are summarized using descriptive statistics such as:

- Count
- Mean
- Standard deviation
- Minimum
- Quartiles
- Maximum

These statistics help identify unusual distributions, potential outliers, and impossible values that may require preprocessing.

In [58]:
df.describe().T

                count       mean        std   min   25%   50%   75%    max
age            3194.0  29.477145   8.251467  -5.0  23.0  29.0  35.0  130.0
distance_km    3258.0  24.696071  10.311346   8.3  16.0  25.7  33.1   41.8
discount_inr   3074.0  14.365973  31.070065   0.0   0.0   0.0   8.0  203.0
rating         2183.0   3.798443   1.163396   1.0   3.0   4.0   5.0    5.0
occupancy_pct  2878.0  58.313343  25.073318  15.1  36.7  58.5  79.5  138.8

## Statistical Summary of Categorical Features

Categorical variables are summarized to identify:

- Total observations
- Number of unique categories
- Most frequent category
- Frequency of the most common category

Understanding categorical features helps identify inconsistent spellings, rare categories, and potential standardization requirements.

In [59]:
categorical_summary = (
    df.select_dtypes(include="object")
      .describe()
      .T
)

categorical_summary

                    count unique               top  freq
trip_id              3258   3200         TRP002507     2
booking_id           3258   3200        BK70609800     2
customer_id          3258   1251         CUST00449     9
customer_name        3258    866         Isha Shah    22
gender               3258     11            Female   451
city                 3258     12              Pune   546
route_id             3258     60           RTCH050    69
route_name           3258     60  Tambaram - Adyar    69
origin_stop          3258     40        Thane West   225
destination_stop     3258     38        Magarpatta   168
bus_number           3258    160        KA03CF1058    39
bus_type             3258      4     Non-AC Seater   839
driver_id            3258     90           DRV0082    49
driver_name          3226     88      Sanjay Desai    69
trip_date            3258   1113        2024-07-22    12
scheduled_departure  3258    204             18:15    41
actual_departure     2878    768             18:15    26
scheduled_arrival    3258    956             09:42    12
actual_arrival       2538    915             20:55    11
fare_inr             3258    953                 0   317
payment_mode         2878      6               UPI   498
booking_channel      3258      4           Website   861
seat_number          3258     60                D7    76
trip_status          3258      4         Completed  2148
cancellation_reason   720      6  Customer Request   315
weather              3258      6               Fog   579
is_peak_hour         3258      6             False   671
subscription_type    3258      4    Corporate Plan   839
device_type          3258      3           Android  1107
gps_enabled          3258     10              true   614
complaint_raised     3258      4                 0  1544

## Automatic Feature Categorization

To make the preprocessing pipeline adaptable to future datasets, features are automatically categorized based on their data types.

This dynamic approach ensures that preprocessing steps remain applicable even if additional columns are introduced or existing columns are modified.

In [60]:
numerical_cols = df.select_dtypes(include=np.number).columns.tolist()

categorical_cols = df.select_dtypes(include="object").columns.tolist()

datetime_cols = df.select_dtypes(include=["datetime64[ns]"]).columns.tolist()

print(f"Numerical Features   : {len(numerical_cols)}")
print(numerical_cols)

print("\nCategorical Features :", len(categorical_cols))
print(categorical_cols)

print("\nDatetime Features    :", len(datetime_cols))
print(datetime_cols)

Numerical Features   : 5
['age', 'distance_km', 'discount_inr', 'rating', 'occupancy_pct']

Categorical Features : 31
['trip_id', 'booking_id', 'customer_id', 'customer_name', 'gender', 'city', 'route_id', 'route_name', 'origin_stop', 'destination_stop', 'bus_number', 'bus_type', 'driver_id', 'driver_name', 'trip_date', 'scheduled_departure', 'actual_departure', 'scheduled_arrival', 'actual_arrival', 'fare_inr', 'payment_mode', 'booking_channel', 'seat_number', 'trip_status', 'cancellation_reason', 'weather', 'is_peak_hour', 'subscription_type', 'device_type', 'gps_enabled', 'complaint_raised']

Datetime Features    : 0
[]

## Missing Value Analysis

Missing values are one of the most common data quality issues encountered in real-world datasets. They can arise due to incomplete data collection, system failures, manual entry errors, or unavailable information.

Before applying any imputation or removal techniques, it is important to identify:

- Total missing values
- Missing values in each feature
- Percentage of missing values
- Features completely free from missing data
- Features requiring preprocessing

This assessment helps determine the most appropriate strategy for handling missing values during the data cleaning phase.

In [61]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage (%)": (
        df.isnull().mean()*100
    ).round(2)
})

missing_summary = missing_summary.sort_values(
    by="Missing Count",
    ascending=False
)

missing_summary

                     Missing Count  Missing Percentage (%)
cancellation_reason           2538                   77.90
rating                        1075                   33.00
actual_arrival                 720                   22.10
actual_departure               380                   11.66
payment_mode                   380                   11.66
occupancy_pct                  380                   11.66
discount_inr                   184                    5.65
age                             64                    1.96
driver_name                     32                    0.98
customer_id                      0                    0.00
booking_id                       0                    0.00
trip_id                          0                    0.00
customer_name                    0                    0.00
bus_number                       0                    0.00
origin_stop                      0                    0.00
destination_stop                 0                    0.00
route_name                       0                    0.00
gender                           0                    0.00
city                             0                    0.00
route_id                         0                    0.00
scheduled_arrival                0                    0.00
scheduled_departure              0                    0.00
driver_id                        0                    0.00
trip_date                        0                    0.00
bus_type                         0                    0.00
booking_channel                  0                    0.00
distance_km                      0                    0.00
fare_inr                         0                    0.00
trip_status                      0                    0.00
seat_number                      0                    0.00
weather                          0                    0.00
is_peak_hour                     0                    0.00
subscription_type                0                    0.00
device_type                      0                    0.00
gps_enabled                      0                    0.00
complaint_raised                 0                    0.00

In [62]:
missing_cols = missing_summary[
    missing_summary["Missing Count"] > 0
]

if len(missing_cols)==0:
    print("✅ No missing values found.")
else:
    display(missing_cols)

                     Missing Count  Missing Percentage (%)
cancellation_reason           2538                   77.90
rating                        1075                   33.00
actual_arrival                 720                   22.10
actual_departure               380                   11.66
payment_mode                   380                   11.66
occupancy_pct                  380                   11.66
discount_inr                   184                    5.65
age                             64                    1.96
driver_name                     32                    0.98

## Duplicate Record Analysis

Duplicate records can occur due to repeated data collection, system synchronization issues, or manual entry errors.

Duplicate observations may bias statistical analysis and machine learning models. Therefore, identifying duplicate rows before cleaning is an essential preprocessing step.

This section reports:

- Total duplicate rows
- Percentage of duplicate records
- Sample duplicate observations (if any)

In [63]:
duplicate_rows = df.duplicated().sum()

duplicate_percentage = (
    duplicate_rows / len(df)
)*100

print("="*60)
print("DUPLICATE RECORD ANALYSIS")
print("="*60)

print(f"Duplicate Rows : {duplicate_rows}")

print(f"Duplicate Percentage : {duplicate_percentage:.2f}%")

============================================================
DUPLICATE RECORD ANALYSIS
============================================================
Duplicate Rows : 58
Duplicate Percentage : 1.78%

In [64]:
if duplicate_rows > 0:
    display(df[df.duplicated()].head())
else:
    print("✅ No duplicate records detected.")

,trip_id,booking_id,customer_id,customer_name,gender,age,city,route_id,route_name,origin_stop,destination_stop,bus_number,bus_type,driver_id,driver_name,trip_date,scheduled_departure,actual_departure,scheduled_arrival,actual_arrival,distance_km,fare_inr,discount_inr,payment_mode,booking_channel,seat_number,trip_status,cancellation_reason,rating,occupancy_pct,weather,is_peak_hour,subscription_type,device_type,gps_enabled,complaint_raised
727,TRP001282,BK96417047,CUST00340,Karan Pillai,Male,19.0,Chennai,RTCH049,Velachery - Tambaram,Velachery,Tambaram,TN37CF5930,Premium AC,DRV0071,Kavya Gupta,2024-09-29,11:05,11:04,12:33,12:32,37.6,462,73.0,Credit Card,Corporate Portal,B8,Completed,NaN,4.0,23.2,Heavy Rain,False,Weekly Pass,iOS,Yes,0
802,TRP000356,BK36212551,CUST00452,Vivaan Agarwal,Other,30.0,Bangalore,RTBA025,Hebbal - Marathahalli,Hebbal,Marathahalli,KA38CF3426,Premium AC,DRV0032,Ashok Shah,2024-10-12,20:10,20:10,20:37,20:37,9.2,123,0.0,UPI,Kiosk,D9,Completed,NaN,5.0,72.7,Heavy Rain,False,Monthly Pass,Android,Yes,No
1022,TRP002222,BK69043200,CUST00717,Arjun Bansal,male,33.0,Pune,RTPU019,Kothrud - Magarpatta,Kothrud,Magarpatta,MH14CF8933,Non-AC Seater,DRV0029,Ayaan Joshi,16-Jun-2024,09:15,09:15,09:42,09:42,10.7,₹109,0.0,Wallet,Mobile App,A13,Completed,NaN,1.0,67.8,Rain,False,Corporate Plan,Web,True,No
1038,TRP002079,BK86993341,CUST00816,Rajesh Kapoor,Male,46.0,Hyderabad,RTHY038,HITEC City - Kondapur,HITEC City,Kondapur,TS29CF4501,Premium AC,DRV0047,Rohan Bansal,2024-03-14,17:45,17:45,18:28,18:28,14.1,₹256,0.0,UPI,Mobile App,B14,Completed,NaN,4.0,54.3,Haze,False,Single Ride,iOS,Yes,0
1113,TRP000635,BK41032607,CUST01389,Krishna Kapoor,Female,28.0,Mumbai,RTMU002,Andheri East - Thane West,Andheri East,Thane West,MH05CF1964,AC Sleeper,DRV0044,Kalpana Bhat,25/02/2024,11:00,11:05,12:18,12:23,24.5,266,56.0,Debit Card,Website,A8,Completed,NaN,5.0,55.4,Clear,No,Weekly Pass,iOS,Yes,No

## Duplicate Feature Detection

Sometimes datasets contain multiple columns storing identical information under different names. Such redundant features unnecessarily increase memory usage and may negatively affect analysis.

This section identifies columns having exactly the same values throughout the dataset.

In [65]:
duplicate_columns = []

for i in range(len(df.columns)):
    col1 = df.columns[i]

    for j in range(i+1, len(df.columns)):
        col2 = df.columns[j]

        if df[col1].equals(df[col2]):
            duplicate_columns.append((col1, col2))

if duplicate_columns:
    print("Duplicate Columns Found:\n")
    for pair in duplicate_columns:
        print(pair)
else:
    print("✅ No duplicate columns found.")

✅ No duplicate columns found.

## Constant Feature Detection

Constant features contain only a single unique value throughout the dataset.

Since these columns provide no variability or predictive information, they are generally removed during preprocessing.

In [66]:
constant_cols = []

for col in df.columns:

    if df[col].nunique(dropna=False) == 1:
        constant_cols.append(col)

print("Constant Columns Found:")

if constant_cols:
    print(constant_cols)
else:
    print("✅ None")

Constant Columns Found:
✅ None

## Quasi-Constant Feature Detection

A quasi-constant feature contains one dominant value appearing in the vast majority of observations (typically more than 95%).

Although not completely constant, these features often contribute very little information and may be considered for removal depending on the application.

In [67]:
threshold = 0.95

quasi_constant = []

for col in df.columns:

    dominant = (
        df[col]
        .value_counts(normalize=True,
                      dropna=False)
        .max()
    )

    if dominant >= threshold:
        quasi_constant.append({
            "Column": col,
            "Dominant Ratio": round(dominant,4)
        })

pd.DataFrame(quasi_constant)

Empty DataFrame
Columns: []
Index: []

## High Cardinality Feature Detection

Categorical variables containing a very large number of unique values are known as high-cardinality features.

Such columns often represent identifiers, names, or free-text attributes. Detecting them early helps determine suitable encoding or transformation strategies during preprocessing.

In [68]:
high_cardinality = []

for col in categorical_cols:

    unique = df[col].nunique()

    ratio = unique/len(df)

    if unique > 50:

        high_cardinality.append({
            "Column": col,
            "Unique Values": unique,
            "Unique Ratio": round(ratio,3)
        })

pd.DataFrame(high_cardinality)

                 Column  Unique Values  Unique Ratio
0               trip_id           3200         0.982
1            booking_id           3200         0.982
2           customer_id           1251         0.384
3         customer_name            866         0.266
4              route_id             60         0.018
5            route_name             60         0.018
6            bus_number            160         0.049
7             driver_id             90         0.028
8           driver_name             88         0.027
9             trip_date           1113         0.342
10  scheduled_departure            204         0.063
11     actual_departure            768         0.236
12    scheduled_arrival            956         0.293
13       actual_arrival            915         0.281
14             fare_inr            953         0.293
15          seat_number             60         0.018

## Identifier Feature Detection

Identifier columns uniquely distinguish individual records rather than describing their characteristics.

Examples include booking IDs, customer IDs, transaction IDs, and ticket numbers.

Such features are generally excluded from statistical analysis and predictive modeling but retained for reference purposes.

In [69]:
identifier_columns = []
for col in df.columns:
    unique = df[col].nunique()
    if unique == len(df):
        identifier_columns.append(col)
print("Possible Identifier Columns:\n")

for col in identifier_columns:
    print("•", col)

Possible Identifier Columns:

## Leading and Trailing Whitespace Detection

Extra spaces before or after text values are common data entry issues. Although visually similar, values such as **"Mumbai"** and **" Mumbai "** are treated as different categories during analysis.

This section identifies columns containing leading or trailing whitespace characters so they can be standardized during the cleaning phase.

whitespace_columns = []

for col in categorical_cols:

    if df[col].dtype == "object":

        has_whitespace = df[col].dropna().astype(str).apply(
            lambda x: x != x.strip()
        ).any()

        if has_whitespace:
            whitespace_columns.append(col)

print("=" * 60)
print("LEADING / TRAILING WHITESPACE ANALYSIS")
print("=" * 60)

if whitespace_columns:
    print("Columns containing extra spaces:\n")
    for col in whitespace_columns:
        print(f"• {col}")
else:
    print("✅ No leading or trailing whitespaces detected.")

## Empty String Detection

Some datasets store missing information as blank strings rather than proper null values. Since these values are not recognized as missing by default, they must first be identified before appropriate preprocessing techniques can be applied.

In [70]:
empty_summary = {}

for col in categorical_cols:

    count = (df[col].astype(str).str.strip() == "").sum()

    if count > 0:
        empty_summary[col] = count

print("=" * 60)
print("EMPTY STRING ANALYSIS")
print("=" * 60)

if empty_summary:

    display(
        pd.DataFrame(
            empty_summary.items(),
            columns=["Column", "Empty Strings"]
        )
    )

else:
    print("✅ No empty strings found.")

============================================================
EMPTY STRING ANALYSIS
============================================================
✅ No empty strings found.

## Invalid Missing Value Placeholder Detection

In many datasets, missing information is represented using placeholders such as:

- NA
- N/A
- Null
- None
- Unknown
- Missing
- -
- ?

These values are not automatically recognized as missing and should be identified before cleaning.

In [71]:
# =====================================================
# Placeholder Detection
# =====================================================

placeholders = [
    "",
    " ",
    "NA",
    "N/A",
    "NULL",
    "Null",
    "null",
    "None",
    "NONE",
    "Unknown",
    "UNKNOWN",
    "-",
    "--",
    "?",
    "Missing"
]

placeholder_report = {}

for col in categorical_cols:

    count = df[col].astype(str).isin(placeholders).sum()

    if count > 0:
        placeholder_report[col] = count

print("PLACEHOLDER ANALYSIS")


if placeholder_report:

    display(
        pd.DataFrame(
            placeholder_report.items(),
            columns=["Column", "Placeholder Count"]
        )
    )

else:
    print("✅ No placeholder values detected.")

PLACEHOLDER ANALYSIS
✅ No placeholder values detected.

## Mixed Data Type Detection

Columns containing multiple data types may indicate inconsistent data entry or import issues. Such inconsistencies can interfere with numerical computations, statistical analysis, and machine learning algorithms.

This section identifies columns that contain more than one Python data type.

In [72]:
# =====================================================
# Mixed Data Type Detection
# =====================================================

mixed_columns = []

for col in df.columns:

    unique_types = df[col].dropna().map(type).nunique()

    if unique_types > 1:

        mixed_columns.append({
            "Column": col,
            "Number of Types": unique_types,
            "Types": df[col].dropna().map(type).unique()
        })

mixed_df = pd.DataFrame(mixed_columns)

if mixed_df.empty:
    print("✅ No mixed data types detected.")
else:
    display(mixed_df)

✅ No mixed data types detected.

## Case Consistency Analysis

Categorical variables may contain inconsistent capitalization, resulting in duplicate categories that represent the same value.

For example:

- Male
- male
- MALE

Although visually similar, these are treated as separate categories by analytical tools. This section identifies columns that may require case standardization.

In [73]:
case_issues = []

for col in categorical_cols:

    original_unique = (
        df[col]
        .dropna()
        .astype(str)
        .nunique()
    )

    lower_unique = (
        df[col]
        .dropna()
        .astype(str)
        .str.lower()
        .nunique()
    )

    if lower_unique < original_unique:

        case_issues.append({
            "Column": col,
            "Original Categories": original_unique,
            "After Lowercase": lower_unique
        })

case_df = pd.DataFrame(case_issues)

if case_df.empty:
    print("✅ No case inconsistencies detected.")
else:
    display(case_df)

        Column  Original Categories  After Lowercase
0       gender                   11                8
1  gps_enabled                   10                8

## Hidden Character Detection

Hidden characters such as tabs (`\t`), newlines (`\n`), and carriage returns (`\r`) are often introduced during data collection or file imports. These invisible characters can create duplicate categories and interfere with filtering, grouping, and text processing operations.

This section identifies columns that contain such hidden formatting characters.

In [74]:
hidden_columns = []

pattern = r"[\n\r\t]"

for col in categorical_cols:

    found = df[col].astype(str).str.contains(
        pattern,
        regex=True,
        na=False
    ).any()

    if found:
        hidden_columns.append(col)

print("HIDDEN CHARACTER ANALYSIS")


if hidden_columns:
    print("Columns containing hidden characters:\n")
    for col in hidden_columns:
        print(f"• {col}")
else:
    print("✅ No hidden characters detected.")

HIDDEN CHARACTER ANALYSIS
✅ No hidden characters detected.

## Numeric Values Stored as Text

Numeric information is sometimes imported as text due to formatting inconsistencies, special characters, or mixed values within a column.

Identifying such columns allows them to be converted into appropriate numeric data types during the cleaning phase.

In [75]:


possible_numeric = []

for col in categorical_cols:

    converted = pd.to_numeric(df[col], errors="coerce")

    success_rate = converted.notna().mean()

    if success_rate >= 0.90:   # 90% or more values can be numeric

        possible_numeric.append({
            "Column": col,
            "Convertible (%)": round(success_rate * 100, 2)
        })

possible_numeric_df = pd.DataFrame(possible_numeric)

if possible_numeric_df.empty:
    print("✅ No text columns appear to be numeric.")
else:
    display(possible_numeric_df)

✅ No text columns appear to be numeric.

# Data Cleaning

## Create a Backup of the Original Dataset

Before performing any modifications, a copy of the original dataset is created. This ensures that the raw data remains unchanged and provides a reliable reference for comparison, validation, and recovery if required.

All subsequent preprocessing operations are performed on the copied dataset.

In [76]:

df_original = df.copy(deep=True)
df = df.copy(deep=True)

print("Original dataset backed up successfully.")

Original dataset backed up successfully.

## Standardize Column Names

Datasets collected from different sources often contain inconsistent column names due to varying capitalization, spaces, special characters, or formatting styles.

To improve readability and ensure compatibility with Python programming conventions, column names are standardized by:

- Removing leading and trailing spaces
- Converting all names to lowercase
- Replacing spaces with underscores
- Replacing hyphens with underscores
- Removing unnecessary special characters
- Eliminating duplicate underscores

This standardization improves code readability and reduces the likelihood of errors during analysis.

In [77]:
import re

original_columns = df.columns.tolist()

clean_columns = []

for col in df.columns:

    col = str(col)

    # Remove leading/trailing spaces
    col = col.strip()

    # Convert to lowercase
    col = col.lower()

    # Replace spaces and hyphens with underscores
    col = re.sub(r"[\s\-]+", "_", col)

    # Remove special characters except underscore
    col = re.sub(r"[^a-z0-9_]", "", col)

    # Replace multiple underscores
    col = re.sub(r"_+", "_", col)

    # Remove leading/trailing underscores
    col = col.strip("_")

    clean_columns.append(col)

# Handle duplicate column names
seen = {}
final_columns = []

for col in clean_columns:
    if col not in seen:
        seen[col] = 0
        final_columns.append(col)
    else:
        seen[col] += 1
        final_columns.append(f"{col}_{seen[col]}")

df.columns = final_columns

print("Column names standardized successfully.")

Column names standardized successfully.

In [78]:
pd.DataFrame({
    "Original Column Name": original_columns,
    "Standardized Column Name": df.columns
})

   Original Column Name Standardized Column Name
0               trip_id                  trip_id
1            booking_id               booking_id
2           customer_id              customer_id
3         customer_name            customer_name
4                gender                   gender
5                   age                      age
6                  city                     city
7              route_id                 route_id
8            route_name               route_name
9           origin_stop              origin_stop
10     destination_stop         destination_stop
11           bus_number               bus_number
12             bus_type                 bus_type
13            driver_id                driver_id
14          driver_name              driver_name
15            trip_date                trip_date
16  scheduled_departure      scheduled_departure
17     actual_departure         actual_departure
18    scheduled_arrival        scheduled_arrival
19       actual_arrival           actual_arrival
20          distance_km              distance_km
21             fare_inr                 fare_inr
22         discount_inr             discount_inr
23         payment_mode             payment_mode
24      booking_channel          booking_channel
25          seat_number              seat_number
26          trip_status              trip_status
27  cancellation_reason      cancellation_reason
28               rating                   rating
29        occupancy_pct            occupancy_pct
30              weather                  weather
31         is_peak_hour             is_peak_hour
32    subscription_type        subscription_type
33          device_type              device_type
34          gps_enabled              gps_enabled
35     complaint_raised         complaint_raised

## Remove Leading and Trailing Whitespaces

Text-based features frequently contain unnecessary leading or trailing spaces introduced during manual data entry or data import.

Although visually identical, values with extra spaces are treated as distinct categories during grouping, filtering, and statistical analysis.

To improve consistency, leading and trailing whitespace characters are removed from all text-based features.

In [79]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:

    df[col] = df[col].astype(str).str.strip()

print("Leading and trailing whitespaces removed.")

Leading and trailing whitespaces removed.

## Standardize Missing Value Representation

Missing information is often represented using placeholder values rather than true null values. These placeholders are converted into a consistent missing value representation (`NaN`) to simplify subsequent preprocessing tasks such as imputation and missing value analysis.

Standardizing missing values ensures that all missing information is handled uniformly throughout the data cleaning pipeline.

In [80]:

placeholders = [
    "",
    " ",
    "NA",
    "N/A",
    "NULL",
    "Null",
    "null",
    "None",
    "NONE",
    "Unknown",
    "UNKNOWN",
    "Missing",
    "-",
    "--",
    "?"
]

df.replace(placeholders, np.nan, inplace=True)

print("Placeholder values converted to NaN.")

Placeholder values converted to NaN.

## Remove Duplicate Records

Duplicate observations may arise due to repeated data collection, synchronization issues, or manual entry errors.

Removing duplicate records improves data quality, prevents analytical bias, and ensures that each observation represents a unique entity within the dataset.

In [81]:
rows_before = len(df)

duplicates_removed = df.duplicated().sum()

df.drop_duplicates(inplace=True)

rows_after = len(df)


print("DUPLICATE REMOVAL SUMMARY")


print(f"Rows Before Cleaning : {rows_before}")
print(f"Duplicate Rows Found : {duplicates_removed}")
print(f"Rows After Cleaning  : {rows_after}")

DUPLICATE REMOVAL SUMMARY
Rows Before Cleaning : 3258
Duplicate Rows Found : 58
Rows After Cleaning  : 3200

## Reset Dataset Index

After removing records, the DataFrame index may become discontinuous. Resetting the index restores sequential numbering, improving readability and ensuring consistent row referencing throughout the remaining preprocessing steps.

In [82]:
df.reset_index(drop=True, inplace=True)

print("Dataset index reset successfully.")

Dataset index reset successfully.

## Data Type Validation

Correct data types are essential for efficient memory usage, accurate computations, and reliable analysis. However, datasets collected from different sources often contain columns stored with inappropriate data types. For example, numerical values may be stored as text, dates may be represented as strings, and boolean values may appear in multiple formats.

Before converting any column, the existing data types are examined to determine whether they are appropriate for the stored values. This validation step minimizes the risk of incorrect conversions and ensures that subsequent preprocessing operations are performed safely.

In [83]:
dtype_summary = pd.DataFrame({
    "Column": df.columns,
    "Current Data Type": df.dtypes.astype(str).values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique(dropna=False).values
})

display(dtype_summary)

                 Column Current Data Type  Missing Values  Unique Values
0               trip_id            object               0           3200
1            booking_id            object               0           3200
2           customer_id            object               0           1251
3         customer_name            object               0            761
4                gender            object               0              9
5                   age           float64              63             41
6                  city            object               0              6
7              route_id            object               0             60
8            route_name            object               0             60
9           origin_stop            object               0             40
10     destination_stop            object               0             38
11           bus_number            object               0            160
12             bus_type            object               0              4
13            driver_id            object               0             90
14          driver_name            object               0             89
15            trip_date            object               0           1113
16  scheduled_departure            object               0            204
17     actual_departure            object               0            769
18    scheduled_arrival            object               0            956
19       actual_arrival            object               0            916
20          distance_km           float64               0             56
21             fare_inr            object               0            953
22         discount_inr           float64             182            149
23         payment_mode            object               0              7
24      booking_channel            object               0              4
25          seat_number            object               0             60
26          trip_status            object               0              4
27  cancellation_reason            object               0              7
28               rating           float64            1055              6
29        occupancy_pct           float64             373            839
30              weather            object               0              6
31         is_peak_hour            object               0              6
32    subscription_type            object               0              4
33          device_type            object               0              3
34          gps_enabled            object               0             10
35     complaint_raised            object               0              4

## Automatic Numeric Conversion

Numeric information is sometimes imported as text because of inconsistent formatting, delimiters, or missing values.

Instead of manually specifying column names, the preprocessing pipeline automatically identifies object-type columns that predominantly contain numeric values and converts them into the appropriate numeric data type.

This dynamic approach improves reusability across future datasets without requiring code modifications.

In [84]:
converted_numeric = []

for col in df.select_dtypes(include="object").columns:

    converted = pd.to_numeric(df[col], errors="coerce")

    non_null = df[col].notna().sum()

    if non_null == 0:
        continue

    success_rate = converted.notna().sum() / non_null

    if success_rate >= 0.95:

        df[col] = converted

        converted_numeric.append(col)


print("NUMERIC CONVERSION")


if converted_numeric:

    print("Converted Columns:\n")

    for col in converted_numeric:
        print(f"• {col}")

else:
    print("No additional numeric columns detected.")

NUMERIC CONVERSION
No additional numeric columns detected.

## Automatic Date Detection

Dates are frequently stored as text, preventing chronological analysis and time-based feature engineering.

The preprocessing pipeline automatically detects columns that predominantly contain valid date values and converts them into datetime format while preserving invalid entries as missing values.

In [85]:
converted_dates = []

for col in df.select_dtypes(include="object").columns:

    converted = pd.to_datetime(
        df[col],
        errors="coerce",
        infer_datetime_format=True
    )

    non_null = df[col].notna().sum()

    if non_null == 0:
        continue

    success_rate = converted.notna().sum() / non_null

    if success_rate >= 0.95:

        df[col] = converted

        converted_dates.append(col)

print("DATE CONVERSION")

if converted_dates:

    print("Converted Date Columns:\n")

    for col in converted_dates:
        print(f"• {col}")

else:
    print("No date columns detected.")

DATE CONVERSION
Converted Date Columns:

• scheduled_departure
• scheduled_arrival

## Boolean Value Standardization

Binary variables are often represented using different conventions such as **Yes/No**, **True/False**, **Y/N**, or **1/0**. Treating these representations consistently improves data quality and simplifies downstream analysis.

The preprocessing pipeline automatically detects common binary representations and converts them into standard boolean values.

In [86]:
boolean_mapping = {
    "yes": True,
    "no": False,
    "true": True,
    "false": False,
    "y": True,
    "n": False,
    "1": True,
    "0": False
}

boolean_columns = []

for col in df.select_dtypes(include="object").columns:

    values = (
        df[col]
        .dropna()
        .astype(str)
        .str.lower()
        .unique()
    )

    if len(values) <= 2:

        if set(values).issubset(boolean_mapping.keys()):

            df[col] = (
                df[col]
                .astype(str)
                .str.lower()
                .map(boolean_mapping)
            )

            boolean_columns.append(col)

print("BOOLEAN STANDARDIZATION")
if boolean_columns:

    print("Boolean Columns Converted:\n")

    for col in boolean_columns:
        print(f"• {col}")

else:
    print("No boolean columns detected.")

BOOLEAN STANDARDIZATION
No boolean columns detected.

## Numeric Data Type Optimization

Selecting appropriate numeric data types reduces memory consumption while preserving information. Large integer and floating-point types are automatically downcast to smaller compatible formats wherever possible.

This optimization improves computational efficiency, especially when processing large datasets.

In [87]:
for col in df.select_dtypes(include=["int64"]).columns:

    df[col] = pd.to_numeric(
        df[col],
        downcast="integer"
    )

for col in df.select_dtypes(include=["float64"]).columns:

    df[col] = pd.to_numeric(
        df[col],
        downcast="float"
    )

print("Numeric data types optimized.")

Numeric data types optimized.

## Memory Usage Comparison

Efficient preprocessing not only improves data quality but also reduces memory consumption. This section compares the memory usage of the original dataset with that of the cleaned dataset after data type optimization.

memory_before = df_original.memory_usage(deep=True).sum() / (1024**2)
memory_after = df.memory_usage(deep=True).sum() / (1024**2)

comparison = pd.DataFrame({
    "Stage": ["Original", "After Optimization"],
    "Memory Usage (MB)": [
        round(memory_before, 2),
        round(memory_after, 2)
    ]
})

display(comparison)

reduction = ((memory_before - memory_after) / memory_before) * 100

print(f"Memory Reduction: {reduction:.2f}%")

## Missing Value Imputation

Missing values can negatively impact statistical analysis and machine learning algorithms. Since different types of variables have different characteristics, a single imputation strategy is not suitable for every feature.

The preprocessing pipeline applies type-specific imputation strategies:

- **Numerical Features:** Missing values are replaced using the median to reduce the influence of extreme values.
- **Categorical Features:** Missing values are replaced using the most frequent category (mode).
- **Datetime Features:** Missing timestamps are filled using forward filling followed by backward filling to preserve chronological consistency whenever possible.

This adaptive approach ensures that the dataset remains complete while minimizing distortion of the original data distribution.

In [88]:

imputation_summary = []

for col in df.columns:

    missing_before = df[col].isnull().sum()

    if missing_before == 0:
        continue

    # Numerical Columns
    if pd.api.types.is_numeric_dtype(df[col]):

        median = df[col].median()

        df[col].fillna(median, inplace=True)

        strategy = "Median"

    # Datetime Columns
    elif pd.api.types.is_datetime64_any_dtype(df[col]):

        df[col] = df[col].ffill().bfill()

        strategy = "Forward Fill + Backward Fill"

    # Categorical Columns
    else:

        mode = df[col].mode(dropna=True)

        if not mode.empty:
            df[col].fillna(mode.iloc[0], inplace=True)
        else:
            df[col].fillna("Unknown", inplace=True)

        strategy = "Mode"

    imputation_summary.append({
        "Column": col,
        "Strategy": strategy,
        "Values Imputed": missing_before
    })

display(pd.DataFrame(imputation_summary))

          Column Strategy  Values Imputed
0            age   Median              63
1   discount_inr   Median             182
2         rating   Median            1055
3  occupancy_pct   Median             373

## Text Standardization

Text features often contain inconsistent capitalization and irregular spacing introduced during manual data entry or data collection from multiple sources.

To improve consistency, text values are standardized by:

- Removing extra internal spaces
- Converting text into title case
- Preserving missing values

Standardized text improves grouping, filtering, aggregation, and visualization.

In [89]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:

    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
        .str.title()
    )

print("Text features standardized.")

Text features standardized.

## Remove Non-Printable Characters

Hidden or non-printable characters may appear due to file encoding differences or data collection systems. These characters are generally invisible but can affect searching, filtering, grouping, and comparisons.

The preprocessing pipeline removes non-printable characters from all text-based features while preserving the original textual information.

In [90]:
import re

for col in text_columns:

    df[col] = df[col].astype(str).apply(
        lambda x: re.sub(r"[^\x20-\x7E]", "", x)
    )

print("Non-printable characters removed.")

Non-printable characters removed.

## Normalize Whitespace

Multiple consecutive whitespace characters can occur during manual entry or file import. Normalizing whitespace improves textual consistency and prevents duplicate categorical values caused solely by spacing differences.

In [91]:
for col in text_columns:

    df[col] = df[col].str.replace(
        r"\s+",
        " ",
        regex=True
    )

print("Whitespace normalized.")

Whitespace normalized.

## Numerical Range Validation

Extreme or impossible values may result from data entry errors, measurement inaccuracies, or system failures.

This section summarizes the range of every numerical feature, allowing potential anomalies to be identified before any outlier treatment is applied.

In [92]:
range_summary = pd.DataFrame({
    "Minimum": df.select_dtypes(include=np.number).min(),
    "Maximum": df.select_dtypes(include=np.number).max(),
    "Mean": df.select_dtypes(include=np.number).mean().round(2),
    "Median": df.select_dtypes(include=np.number).median().round(2)
})

display(range_summary)

               Minimum     Maximum       Mean     Median
age               -5.0  130.000000  29.500000  29.000000
distance_km        8.3   41.799999  24.740000  25.700001
discount_inr       0.0  203.000000  13.540000   0.000000
rating             1.0    5.000000   3.870000   4.000000
occupancy_pct     15.1  138.800003  58.330002  58.500000

## Impossible Value Detection

Certain numerical features have logical constraints. For example, travel distance, fare amount, passenger count, and delay duration should not contain negative values.

The preprocessing pipeline automatically checks for impossible values in commonly encountered transportation-related attributes and reports them for further review.

In [93]:
rules = {
    "fare": lambda x: x < 0,
    "distance": lambda x: x < 0,
    "passenger": lambda x: x <= 0,
    "delay": lambda x: x < 0,
    "rating": lambda x: (x < 0) | (x > 5),
    "duration": lambda x: x <= 0
}

report = []

for col in df.select_dtypes(include=np.number).columns:

    for keyword, condition in rules.items():

        if keyword in col.lower():

            invalid = condition(df[col]).sum()

            if invalid > 0:

                report.append({
                    "Column": col,
                    "Invalid Records": int(invalid)
                })

if report:
    display(pd.DataFrame(report))
else:
    print("✅ No impossible values detected based on predefined rules.")

✅ No impossible values detected based on predefined rules.

## Outlier Detection Using the Interquartile Range (IQR)

Outliers are observations that deviate significantly from the majority of the data. They may arise due to measurement errors, data entry mistakes, or naturally occurring extreme events.

The Interquartile Range (IQR) method identifies potential outliers without making assumptions about the underlying data distribution.

This step detects potential outliers but does not remove them, allowing informed decisions during subsequent analysis.

In [94]:
# =====================================================
# IQR Outlier Detection
# =====================================================

outlier_summary = []

numeric_columns = df.select_dtypes(include=np.number).columns

for col in numeric_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((df[col] < lower) | (df[col] > upper)).sum()

    outlier_summary.append({
        "Column": col,
        "Outliers": outliers,
        "Outlier (%)": round(outliers / len(df) * 100, 2)
    })

outlier_summary = pd.DataFrame(outlier_summary)

display(outlier_summary.sort_values("Outliers", ascending=False))

          Column  Outliers  Outlier (%)
3         rating      1527        47.72
2   discount_inr       766        23.94
0            age        12         0.38
4  occupancy_pct         3         0.09
1    distance_km         0         0.00

## Z-Score Based Outlier Verification

The Z-score method measures how many standard deviations each observation lies from the mean.

Values with an absolute Z-score greater than three are commonly regarded as potential outliers.

This step complements the IQR method by providing an additional perspective on extreme observations.

In [95]:
zscore_summary = []

for col in numeric_columns:

    if df[col].std() == 0:
        continue

    z_scores = np.abs(stats.zscore(df[col]))

    count = (z_scores > 3).sum()

    zscore_summary.append({
        "Column": col,
        "Extreme Values": int(count)
    })

display(pd.DataFrame(zscore_summary))

          Column  Extreme Values
0            age               7
1    distance_km               0
2   discount_inr             103
3         rating             108
4  occupancy_pct               5

## Rare Category Detection

Categories appearing only a few times may represent genuine but infrequent observations, typographical errors, or inconsistent labeling.

Identifying these categories helps determine whether they should be merged, corrected, or retained.

In [96]:
# =====================================================
# Rare Category Detection
# =====================================================

rare_limit = 5

rare_categories = {}

for col in df.select_dtypes(include="object").columns:

    rare = df[col].value_counts()

    rare = rare[rare <= rare_limit]

    if not rare.empty:
        rare_categories[col] = rare

for col, values in rare_categories.items():

    print("=" * 70)
    print(col.upper())
    print("=" * 70)

    display(values.to_frame("Frequency"))

======================================================================
TRIP_ID
======================================================================

           Frequency
trip_id
Trp002833          1
Trp000450          1
Trp001202          1
Trp002699          1
Trp001631          1
...              ...
Trp001653          1
Trp002802          1
Trp000793          1
Trp002439          1
Trp000768          1

[3200 rows x 1 columns]

======================================================================
BOOKING_ID
======================================================================

            Frequency
booking_id
Bk58823043          1
Bk10507366          1
Bk23071329          1
Bk97550608          1
Bk69828533          1
...               ...
Bk19231279          1
Bk59659578          1
Bk67236768          1
Bk14257322          1
Bk47984879          1

[3200 rows x 1 columns]

======================================================================
CUSTOMER_ID
======================================================================

             Frequency
customer_id
Cust00266            5
Cust00665            5
Cust00784            5
Cust01305            5
Cust00063            5
...                ...
Cust00503            1
Cust01398            1
Cust01325            1
Cust00146            1
Cust00475            1

[1211 rows x 1 columns]

======================================================================
CUSTOMER_NAME
======================================================================

                Frequency
customer_name
Myra Pillai             5
Ramesh Nair             5
Shalini Verma           5
Ayaan Pillai            5
Kalpana Chopra          5
...                   ...
Suresh Sharma           1
Kiara Kulkarni          1
Divya Gupta             1
Aarav Pillai            1
Aditya Bansal           1

[563 rows x 1 columns]

======================================================================
TRIP_DATE
======================================================================

            Frequency
trip_date
2024-08-21          5
2024-03-25          5
01/03/2024          5
2024-09-21          5
2024-03-19          5
...               ...
02/06/2024          1
03/03/2024          1
15/06/2024          1
15/08/2024          1
11/09/2024          1

[972 rows x 1 columns]

======================================================================
ACTUAL_DEPARTURE
======================================================================

                  Frequency
actual_departure
12:55                     5
22:55                     5
16:10                     5
09:52                     5
19:56                     5
...                     ...
18:32                     1
07:14                     1
10:09                     1
16:04                     1
13:07                     1

[625 rows x 1 columns]

======================================================================
ACTUAL_ARRIVAL
======================================================================

                Frequency
actual_arrival
20:23                   5
10:45                   5
09:24                   5
11:38                   5
21:22                   5
...                   ...
21:52                   1
13:44                   1
08:57                   1
00:19                   1
16:09                   1

[842 rows x 1 columns]

======================================================================
FARE_INR
======================================================================

          Frequency
fare_inr
186               5
189               5
350               5
407               5
358               5
...             ...
Inr 132           1
3288              1
770               1
663               1
Inr 106           1

[525 rows x 1 columns]

## Missing Value Verification

Following the preprocessing steps, the dataset is inspected again to verify whether any missing values remain.

This verification ensures that all missing values have been appropriately addressed before exploratory data analysis.

In [97]:
missing_after = df.isnull().sum()

missing_after = missing_after[missing_after > 0]

if missing_after.empty:

    print("✅ No missing values remaining.")

else:

    display(missing_after.to_frame("Missing Values"))

✅ No missing values remaining.

## Final Data Quality Report

A final quality assessment is performed to summarize the overall condition of the cleaned dataset.

The report includes:

- Dataset dimensions
- Duplicate records
- Missing values
- Number of numerical features
- Number of categorical features
- Memory usage

This summary provides a concise overview of the dataset after preprocessing.

In [98]:
quality_report = pd.DataFrame({

    "Metric": [

        "Rows",
        "Columns",
        "Duplicate Rows",
        "Missing Values",
        "Numerical Features",
        "Categorical Features",
        "Memory Usage (MB)"

    ],

    "Value": [

        len(df),

        len(df.columns),

        df.duplicated().sum(),

        df.isnull().sum().sum(),

        len(df.select_dtypes(include=np.number).columns),

        len(df.select_dtypes(include="object").columns),

        round(df.memory_usage(deep=True).sum()/(1024**2),2)

    ]

})

display(quality_report)

                 Metric    Value
0                  Rows  3200.00
1               Columns    36.00
2        Duplicate Rows     0.00
3        Missing Values     0.00
4    Numerical Features     5.00
5  Categorical Features    29.00
6     Memory Usage (MB)     5.12

## Dataset Comparison

To evaluate the impact of preprocessing, the original dataset is compared with the cleaned dataset.

This comparison highlights changes resulting from duplicate removal and preprocessing operations while confirming the overall structure of the cleaned data.

In [99]:
comparison = pd.DataFrame({

    "Property": [

        "Rows",
        "Columns",
        "Duplicate Rows",
        "Missing Values"

    ],

    "Before Cleaning": [

        len(df_original),

        df_original.shape[1],

        df_original.duplicated().sum(),

        df_original.isnull().sum().sum()

    ],

    "After Cleaning": [

        len(df),

        df.shape[1],

        df.duplicated().sum(),

        df.isnull().sum().sum()

    ]

})

display(comparison)

         Property  Before Cleaning  After Cleaning
0            Rows             3258            3200
1         Columns               36              36
2  Duplicate Rows               58               0
3  Missing Values             5753               0

## Final Dataset Structure

The cleaned dataset is inspected one final time to verify that all preprocessing steps have been successfully applied. This final overview confirms the data types, feature counts, and memory usage before beginning exploratory data analysis.

In [100]:
print("FINAL DATASET INFORMATION")

df.info()

FINAL DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 36 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   trip_id              3200 non-null   object
 1   booking_id           3200 non-null   object
 2   customer_id          3200 non-null   object
 3   customer_name        3200 non-null   object
 4   gender               3200 non-null   object
 5   age                  3200 non-null   float32
 6   city                 3200 non-null   object
 7   route_id             3200 non-null   object
 8   route_name           3200 non-null   object
 9   origin_stop          3200 non-null   object
 10  destination_stop     3200 non-null   object
 11  bus_number           3200 non-null   object
 12  bus_type             3200 non-null   object
 13  driver_id            3200 non-null   object
 14  driver_name          3200 non-null   object
 15  trip_date            3200 non-null   object
 16  scheduled_departure  3200 non-null   datetime64[ns]
 17  actual_departure     3200 non-null   object
 18  scheduled_arrival    3200 non-null   datetime64[ns]
 19  actual_arrival       3200 non-null   object
 20  distance_km          3200 non-null   float32
 21  fare_inr             3200 non-null   object
 22  discount_inr         3200 non-null   float32
 23  payment_mode         3200 non-null   object
 24  booking_channel      3200 non-null   object
 25  seat_number          3200 non-null   object
 26  trip_status          3200 non-null   object
 27  cancellation_reason  3200 non-null   object
 28  rating               3200 non-null   float32
 29  occupancy_pct        3200 non-null   float32
 30  weather              3200 non-null   object
 31  is_peak_hour         3200 non-null   object
 32  subscription_type    3200 non-null   object
 33  device_type          3200 non-null   object
 34  gps_enabled          3200 non-null   object
 35  complaint_raised     3200 non-null   object
dtypes: datetime64[ns](2), float32(5), object(29)
memory usage: 837.6+ KB

## Export the Cleaned Dataset

The cleaned dataset is exported as a CSV file so it can be reused for exploratory data analysis, visualization, machine learning, or future projects without repeating the preprocessing steps.

In [101]:
output_file = "cityflo_bus_service_metro_cities_cleaned.csv"

df.to_csv(output_file, index=False)

print(f"Cleaned dataset saved as '{output_file}'")

Cleaned dataset saved as 'cityflo_bus_service_metro_cities_cleaned.csv'